CREATE TABLE IF NOT EXISTS STATE (
    `STATE_ID` VARCHAR(4) CHARACTER SET utf8,
    `State` VARCHAR(17) CHARACTER SET utf8
);
INSERT INTO STATE VALUES
    ('S01','Andhra Pradesh'),
    ('S02','Arunachal Pradesh'),
    ('S03','Assam'),
    ('S04','Bihar'),
    ('S05','Chhattisgarh'),
    ('S06','Telangana'),
    ('S07','Gujarat'),
    ('S08','Haryana'),
    ('S09','Himachal Pradesh'),
    ('S10','J&K'),
    ('S11','Jharkhand'),
    ('S12','Karnataka'),
    ('S13','Kerela'),
    ('S14','Madhya Pradesh'),
    ('S15','Maharashtra'),
    ('S16','Manipur'),
    ('S17','Meghalaya'),
    ('S18','Mizoram'),
    ('S19','Nagaland'),
    ('S20','Orissa'),
    ('S21','Punjab'),
    ('S22','Rajasthan'),
    ('S23','Sikkim'),
    ('S24','Tamil Nadu'),
    ('S25','Tripura'),
    ('S26','Uttar Pradesh'),
    ('S27','Uttarakhand'),
    ('S28','West Bengal'),
    ('S29','Goa'),
    ('UT01','Delhi'),
    ('UT02','Andaman & Nicobar'),
    ('UT03','Chandigarh'),
    ('UT04','Dadra&NagarHavei'),
    ('UT05','Daman & Diu'),
    ('UT06','Lakshwadeep'),
    ('UT07','Pondicherry');
